dbt_masterclass_yt:
  outputs:
    dev:
      catalog: dbt_dev
      host: 
      http_path: 
      schema: default
      threads: 1
      token: 
      type: databricks
    prod:
      catalog: dbt_prod
      host: 
      http_path: 
      schema: default
      threads: 1
      token: 
      type: databricks
  target: dev
